using SecondSightWeb.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace SecondSightWeb.Areas.Admin.Models.ViewModel
{
    public class PurchaseOrderViewModel
    {
        [DisplayName("Purchase Order Id")]
        public int POID { get; set; }
        [DisplayName("Supplier Name")]
        public string SupplierName { get; set; }
        [DisplayName("Purchase Order Date")]
        public DateTime PODate { get; set; }
        [DisplayName("Estimated Amount")]
        public decimal? PreviewAmount { get; set; }
        [DisplayName("Purchase Order Generated By")]
        public string GeneratedBy { get; set; }
        [DisplayName("Purchase Order Generated Time")]
        public DateTime GeteratedTime { get; set; }

    }
}